### ISSUE TITLE
First letter of legendary master handle is black on standing pages

### ISSUE THREAD

**Issue by user202729** [GaurangTandon/codeforces-darktheme#25]
For example: https://codeforces.com/contest/1329/standings

Possible fix:
```css

span.user-legendary::first-letter, a.user-legendary::first-letter {
    color: #fff !important;
}
```
